In [55]:
#jacobi method:

import numpy as np
def jacobi(A, b, x0, max_iter, tol):
    n = len(A)
    x = x0.copy()
    for i in range(max_iter):
        x_new = np.zeros_like(x)
        for j in range(n):
            s = sum(A[j, k] * x[k] for k in range(n) if k != j)
            x_new[j] = (b[j] - s) / A[j, j]
        if np.allclose(x, x_new, rtol=tol):
            return x_new
        x = x_new
    return x
#Edit the following values:
A = np.array([[2.0,1.0],[1.0,2.0]])

b = np.array([3.0,3.0])

# This will be given:
x0 = np.array([0.0,0.0])

#Edit the max iterations:
x = jacobi(A, b, x0, max_iter=5, tol=1e-6)
print(x)

[1.03125 1.03125]


In [1]:
#Gauss Siedel method
import numpy as np

def gauss_seidel(A, b, x0, max_iter, tol):
    n = len(A)
    x = x0.copy()
    for i in range(max_iter):
        x_new = np.zeros_like(x)
        for j in range(n):
            s = sum(A[j, k] * x_new[k] for k in range(n) if k < j)
            s += sum(A[j, k] * x[k] for k in range(n) if k > j)
            x_new[j] = (b[j] - s) / A[j, j]
        if np.allclose(x, x_new, rtol=tol):
            return x_new
        x = x_new
    return x

A = np.array([[2.0,-1.0,0.0],[-1.0,1.0,3.0],[1.0,0.0,1.0]])
b = np.array([1.0,3.0,2.0])
x0 = np.array([0.0,0.0,0.0])

x = gauss_seidel(A, b, x0, max_iter=1, tol=1e-6)
print(x)

[0.5 3.5 1.5]


In [33]:
import numpy as np

def LU_factorization(A):
    n = len(A)
    L = np.eye(n)
    U = A.copy()
    for j in range(n):
        for i in range(j+1, n):
            L[i, j] = U[i, j] / U[j, j]
            for k in range(j, n):
                U[i, k] = U[i, k] - L[i, j] * U[j, k]
    return L, U

A = np.array([[4.0,-1.0,-1.0],[2.0,4.0,2.0],[1.0,2.0,4.0]])
L, U = LU_factorization(A)
print(L)
print(U)

[[1.   0.   0.  ]
 [0.5  1.   0.  ]
 [0.25 0.5  1.  ]]
[[ 4.  -1.  -1. ]
 [ 0.   4.5  2.5]
 [ 0.   0.   3. ]]


In [29]:
import numpy as np

def gaussian_elimination(A, b):
    n = len(A)
    for i in range(n):
        pivot = i
        for j in range(i+1, n):
            if abs(A[j, i]) > abs(A[pivot, i]):
                pivot = j
        A[[i, pivot], :] = A[[pivot, i], :]
        b[[i, pivot]] = b[[pivot, i]]
        for j in range(i+1, n):
            m = A[j, i] / A[i, i]
            A[j, i:] = A[j, i:] - m * A[i, i:]
            b[j] = b[j] - m * b[i]
    x = np.zeros(n)
    for i in range(n-1, -1, -1):
        x[i] = (b[i] - np.dot(A[i, i+1:], x[i+1:])) / A[i, i]
    return x
#Edit these arrays:

A = np.array([[4,-1,-1],[0,4,2],[0,0,3]])
b = np.array([9,-10,5])

x = gaussian_elimination(A, b)
print(x)

[ 1.83333333 -3.33333333  1.66666667]


In [59]:
#Sparse matrices
import numpy as np

A_real = np.array([1.0, 1.0, 1.0, -1.0, 1.0], dtype=np.float64)
I_row = np.array([1.0,1.0,2.0,2.0,3.0], dtype=np.int32)
I_col = np.array([1.0,3.0,1.0,2.0,2.0], dtype=np.int32) 

nonzero = len(A_real)
dim = 4
y = np.zeros(dim) + 1.0
z = np.zeros(dim)

for k in range(nonzero):
    z[I_row[k]] += A_real[k] * y[I_col[k]]

print(z)

[0. 2. 0. 1.]


In [57]:
import numpy as np

def gaussian_elimination_with_pivoting(A, b):
    n = len(A)
    # perform Gaussian elimination
    for i in range(n):
        # find pivot row
        pivot = i
        for j in range(i + 1, n):
            if abs(A[j][i]) > abs(A[pivot][i]):
                pivot = j
        # swap rows
        if pivot != i:
            A[[i, pivot]] = A[[pivot, i]]
            b[[i, pivot]] = b[[pivot, i]]
        # perform elimination
        for j in range(i + 1, n):
            m = A[j][i] / A[i][i]
            A[j,i:] = A[j,i:] - m * A[i,i:]
            b[j] = b[j] - m * b[i]
    # perform back-substitution
    x = np.zeros(n)
    for i in range(n-1, -1, -1):
        x[i] = (b[i] - np.dot(A[i,i+1:], x[i+1:])) / A[i][i]
    return x

# Example usage:
# Solve the system of linear equations 3x + y = 9 and x + 2y = 8
A = np.array([[0.0,1.0,0.0],[1.0,1.001,1.0],[100.0,100.0,0.0]])
b = np.array([0.0,1002.0,200.0])
x = gaussian_elimination_with_pivoting(A, b)
print(x) # Output: [1. 2.]

[   2.    0. 1000.]


In [82]:
import numpy as np

def jacobi(A, b, x0, max_iterations=100, tolerance=1e-6):
    n = len(b)
    x = x0.copy()
    D = np.diag(A)
    R = A - np.diagflat(D)
    for i in range(max_iterations):
        x_new = (b - np.dot(R, x)) / D
        if np.allclose(x, x_new, rtol=tolerance):
            break
        x = x_new
    return x

# Example usage
A = np.array([[2, 1, 0], [1, 2, 1], [0, 1, 2]])
b = np.array([1, 2, 3])
x0 = np.zeros(3)
x = jacobi(A, b, x0)
print(x)

[0.49999999 0.         1.49999999]


In [18]:
def Euler_method(t0, d0, dt, n):
    '''
    Input:    initial value d0, time setp dt, and total computational steps n
    Output:   array d(n+1) with d[0] = d0, d[1] = d(0.01), d[2]=d(0.01) ... d[100] = d(1.00)
    '''
    d = np.zeros(n+1)
    d[0] = d0

    t = np.zeros(n+1)
    for i in range(n+1):
        t[i] = t0 + i*dt

    # Implement Euler's method
    for i in range(n):
        d[i+1] = d[i] + dt * f(t[i], d[i])

    return t, d
# The right-hand side function of the differential equation
def f(t, d):
    return (2* d**0.5)

# The exact solution of the differential equation
def d_exact(t):
    return t**2

t0 = float(0.0)
d0 = float(1.0)
dt = float(0.01)
n = int(100)

t, d = Euler_method(0.01, 0.1, 0.1, 10)

print(t)
print(d)


# de = np.zeros(n+1)
# for i in range(n+1):
#     de[i] = d_exact(t[i])
    

# import matplotlib.pyplot as plt
# fig = plt.figure()
# plt.plot(t, d, "-r", label="Euler method")
# plt.plot(t, de, "-b", label="Exact solution")
# plt.legend(loc="upper left")
# plt.xlabel("t")
# plt.ylabel("d")
# plt.grid()
# plt.show()

[0.01 0.11 0.21 0.31 0.41 0.51 0.61 0.71 0.81 0.91 1.01]
[0.1        0.16324555 0.24405287 0.34285628 0.45996414 0.59560546
 0.74995642 0.92315646 1.11531853 1.32653581 1.55688648]


In [14]:
#Euler's method using midpoint

import numpy as np

def euler_midpoint(f, y0, t0, tf, h):
    """
    Solve an ODE using the midpoint method.

    Parameters:
        f (function): The ODE to be solved.
        y0 (float): The initial value of the solution.
        t0 (float): The initial time.
        tf (float): The final time.
        h (float): The time step size.

    Returns:
        t (array): The time steps.
        y (array): The solution at each time step.
    """
    t = np.arange(t0, tf, h)
    y = np.zeros(len(t))
    y[0] = y0

    for i in range(1, len(t)):
        k1 = h * f(t[i-1], y[i-1])
        k2 = h * f(t[i-1] + h/2, y[i-1] + k1/2)
        y[i] = y[i-1] + k2

    return t, y

def ode(t, y):
    return (2* y**0.5)

#print(euler_midpoint(ode,2,0,1,0.5))

t,y = euler_midpoint(ode, 0.01, 0.1, 10, 0.1)

print(t)
print(y)

[0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8
 1.9 2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 3.  3.1 3.2 3.3 3.4 3.5 3.6
 3.7 3.8 3.9 4.  4.1 4.2 4.3 4.4 4.5 4.6 4.7 4.8 4.9 5.  5.1 5.2 5.3 5.4
 5.5 5.6 5.7 5.8 5.9 6.  6.1 6.2 6.3 6.4 6.5 6.6 6.7 6.8 6.9 7.  7.1 7.2
 7.3 7.4 7.5 7.6 7.7 7.8 7.9 8.  8.1 8.2 8.3 8.4 8.5 8.6 8.7 8.8 8.9 9.
 9.1 9.2 9.3 9.4 9.5 9.6 9.7 9.8 9.9]
[1.00000000e-02 3.82842712e-02 8.63885904e-02 1.54441666e-01
 2.42473645e-01 3.50494987e-01 4.78510236e-01 6.26521678e-01
 7.94530582e-01 9.82537713e-01 1.19054355e+00 1.41854843e+00
 1.66655256e+00 1.93455612e+00 2.22255920e+00 2.53056191e+00
 2.85856431e+00 3.20656644e+00 3.57456836e+00 3.96257010e+00
 4.37057167e+00 4.79857311e+00 5.24657443e+00 5.71457565e+00
 6.20257677e+00 6.71057782e+00 7.23857879e+00 7.78657970e+00
 8.35458055e+00 8.94258134e+00 9.55058210e+00 1.01785828e+01
 1.08265835e+01 1.14945841e+01 1.21825847e+01 1.28905853e+01
 1.36185858e+01 1.43665864e+01 1.51345869e+01 1.5

In [37]:
def bisect(func, a, b, tol=1e-8):
    """
    Finds a root of the function func within the interval [a,b] using bisection method.
    :param func: function to find root of
    :param a: lower interval limit
    :param b: upper interval limit
    :param tol: tolerance for root approximation
    :return: root of function
    """
    if func(a) * func(b) >= 0:
        print("Bisect method fails.")
        return None
    c = a
    count = 0
    max_itr = 0
    while (b-a) >= tol and (max_itr == 2 or max_itr == 1 or max_itr == 0):
        c = (a+b)/2
        count += 1
        if func(c) == 0.0:
            break
        if func(c)*func(a) < 0:
            b = c
        else:
            a = c
        max_itr = max_itr + 1
    print(max_itr)
    print("Number of iterations:", count)
    return c

def f(x): return x**2 - 2
root = bisect(f, 0, 2, tol=1e-8)
print(root)

3
Number of iterations: 3
1.25


In [31]:
import numpy as np

def newton_raphson(func, dfunc, x0, tol=1e-5, maxiter=100):
    """
    Finds a root of the function func using Newton-Raphson method.
    :param func: function to find root of
    :param dfunc: derivative of function
    :param x0: initial guess of root
    :param tol: tolerance for root approximation
    :param maxiter: maximum number of iterations
    :return: root of function
    """
    xn = x0
    try:
        for n in range(0, maxiter):
            fxn = func(xn)
            if abs(fxn) < tol:
                return xn
            dfxn = dfunc(xn)
            if dfxn == 0:
                raise ValueError("Derivative is zero. Try again")
            xn = xn - fxn/dfxn
    except ValueError as e:
        print(e)
    return xn
def f(x): return x**3 + 2*x**2 + x + 1
def df(x): return 3*x**2 + 4 * x + 1
root = newton_raphson(f, df, 0)
print(root)

Derivative is zero. Try again
-1.0


In [27]:
def secant(f, x0, x1, tol):
    x = x1
    it = 0
    while abs(f(x)) > tol:   # iterate until less than or eq tol
        x = x - f(x1) *(x1-x0) / (f(x1) - f(x0))  # apply one Newton iteration
        x0 = x1
        x1 = x
        it = it + 1

    return x, it

f = lambda x: x * (x-3)**2

root,itr = secant(f,4,5, 1e-6)
print(root)
print(itr)

3.000491363419608
17


In [2]:
#Least Square Fitting

import numpy as np

# Define the matrix
A = np.array([[1,-1,1],[1,-0.5,0.25],[1,0,0],[1,0.5,0.25],[1,1,1]])

# Transpose the matrix using the numpy.transpose() function
A_transposed = np.transpose(A)
C = np.dot(A_transposed, A)
B = np.array([1,0.5,0,0.5,2])
D = np.dot(A_transposed, B)
print(C)
print(D)
X = np.linalg.solve(C, D)
print(X)

[[5.    0.    2.5  ]
 [0.    2.5   0.   ]
 [2.5   0.    2.125]]
[4.   1.   3.25]
[0.08571429 0.4        1.42857143]


In [6]:
#
import numpy as np
from scipy.optimize import least_squares

# Define the function to fit
def func(x, a, b,c):
    return a*x*x + b*x + c

# Define the residuals (difference between data and model)
def residuals(p, y, x):
    return y - func(x, *p)

# Initial guess for the parameters
x = np.array([-1, -0.5, 0,0.5,1.0])
y = np.array([1,0.5,0,0.5,2])
p0 = [1, 1,1]

# Perform the least squares optimization
res = least_squares(residuals, p0, args=(y, x))
res.x = np.around(res.x, decimals=4)

# Print the results
print("Fitted parameters: x1 = {2}, x2 = {1} x3 = {0}".format(res.x[0], res.x[1],res.x[2]))


Fitted parameters: x1 = 0.0857, x2 = 0.4 x3 = 1.4286
